name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["source"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false  # 避免错误缓存

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev build-essential zlib1g-dev

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux

      - name: Clean Bundler Cache
        run: rm -rf vendor/bundle Gemfile.lock

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
